const workingTimeData = [
    {
        id: 123456,
        date: 'Sun, 01 Aug 2021 14:56:00 GMT',
        client: 'Kunde 1',
        clientId: 1,
        project: 'Kunde 1 - project 1',
        projectId: 1,
        task: 'Aufgabe 1',
        taskId: 1,
        time: '04:30',
        description: 'task Desc default 1',
    },
    {
        id: 123457,
        date: 'Thu, 03 Dec 2020 15:56:00 GMT',
        client: 'Kunde 2',
        clientId: 2,
        project: 'Kunde 2 - project 2',
        projectId: 4,
        task: 'Aufgabe 2',
        taskId: 2,
        time: '10:45',
        description: 'Task Desc default 2',
    },
    {
        id: 123458,
        date: 'Thu, 03 Dec 2020 15:56:00 GMT',
        client: 'Kunde 2',
        clientId: 2,
        project: 'Kunde 2 - project 2',
        projectId: 4,
        task: 'Aufgabe 2',
        taskId: 2,
        time: '12:30',
        description: 'Task Desc default 2',
    },
];

export default workingTimeData;
